export { PhoneIcon } from '@solar-icons/react/linear/phone'
export { MagnifierIcon } from '@solar-icons/react/linear/magnifier'
export { CheckCircleIcon } from '@solar-icons/react/linear/check-circle'
export { CloseCircleIcon } from '@solar-icons/react/linear/close-circle'
export { CalendarIcon } from '@solar-icons/react/linear/calendar'
export { StopwatchIcon } from '@solar-icons/react/linear/stopwatch'
export { UserCheckIcon } from '@solar-icons/react/linear/user-check'
export { UserPlusIcon } from '@solar-icons/react/linear/user-plus'
export { DangerCircleIcon } from '@solar-icons/react/linear/danger-circle'
export { Logout2Icon as LogoutIcon } from '@solar-icons/react/linear/logout-2'
export { AltArrowDownIcon as ChevronDownIcon } from '@solar-icons/react/linear/alt-arrow-down'
export { LockIcon } from '@solar-icons/react/linear/lock'
export { ChatLineIcon } from '@solar-icons/react/linear/chat-line'
export { CheckSquareIcon } from '@solar-icons/react/linear/check-square'
export { TrashBinTrashIcon as TrashIcon } from '@solar-icons/react/linear/trash-bin-trash'
export { Pen2Icon as EditIcon } from '@solar-icons/react/linear/pen-2'
export { NotesIcon } from '@solar-icons/react/linear/notes'
